// Generates brain-app/api/_nexus/templates.js from nexus-engine/templates/*.pine + catalog.mjs.
// Run:  node nexus-engine/build.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CATALOG } from "./catalog.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(here, "..", "brain-app", "api", "_nexus", "templates.js");

const items = CATALOG.map((t) => {
  const code = fs.readFileSync(path.join(here, "templates", t.src), "utf8").replace(/\r\n/g, "\n").trimEnd() + "\n";
  if (!/^\/\/@version=6/.test(code)) throw new Error(`${t.src}: must start with //@version=6`);
  return { id: t.id, file: t.file, title: t.title, use: t.use, explain: { en: t.explain.en.join("\n"), ar: t.explain.ar.join("\n") }, code };
});

const banner = "// GENERATED by nexus-engine/build.mjs - do not edit by hand. Edit nexus-engine/templates/*.pine and catalog.mjs, then rebuild.\n";
const body = "export const TEMPLATES = " + JSON.stringify(items, null, 1) + ";\n\nexport const TEMPLATE_BY_ID = new Map(TEMPLATES.map((t) => [t.id, t]));\n";
fs.writeFileSync(outFile, banner + body);
console.log("wrote", path.relative(process.cwd(), outFile), items.length, "templates,", (fs.statSync(outFile).size / 1024).toFixed(1), "KB");
